spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/persion_website?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root@mk
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      name: springboot-druid1
      # 初始化连接大小
      initial-size: 20
      # 最大连接数
      max-active: 50
      # 最小空闲连接数
      min-idle: 20
      # 查询超时时间（毫秒）
      query-timeout: 60000
      # 事务查询超时时间（毫秒）
      transaction-query-timeout: 60000
      # 获取连接时最大等待时间（毫秒）
      max-wait: 60000
      # 登录超时时间（毫秒）
      login-timeout: 10000
      # 申请连接时执行validationQuery检测连接是否有效
      test-on-borrow: false
      # 归还连接时执行validationQuery检测连接是否有效
      test-on-return: false
      # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
      test-while-idle: true
      # 1) Destroy线程会检测连接的间隔时间 2) testWhileIdle的判断依据
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 1 FROM DUAL
      # 连接可空闲时间
      min-evictable-idle-time-millis: 30000
      # 打开PSCache，并且指定每个连接上PSCache的大小（Oracle使用）
      #pool-prepared-statements: false
      #max-pool-prepared-statement-per-connection-size: 20
      # 监控统计拦截的filter
      filter: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能，记录慢SQL，阈值5秒
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

      stat-view-servlet:
        # 白名单（不设置则不进行权限校验）
        allow: 127.0.0.1
        # 黑名单（优先级高于白名单）
        #deny: 10.49.12.250
        # 账户
        login-username: minkun
        # 密码
        login-password: 1990326
        # 是否可重置
        reset-enable: false
      web-stat-filter:
        # 不过滤的URL
        exclusions:  /*.js,/*.gif,/*.jpg,/*.png,/*.css,/*.ico,/*druid/*
        # 过滤的URL
        url-pattern: /*

  jpa:
      # 配置 DBMS 类型
      database: MYSQL
      # 配置是否将执行的 SQL 输出到日志
      show-sql: true
      generate-ddl: true
      properties:
        hibernate:
          hbm2ddl:
            # 配置开启自动更新表结构
            auto: update
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  jackson.serialization.indent_output: true

#  redis:
#    database: 1
#    host: localhost
#    port: 6379

  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
    prefix: classpath:/templates/

  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  context-path: /persion-website
  port: 8080
  session_timeout: 1800
  tomcat:
    uri-encoding: UTF-8
    max-http-post-size: 104857600
    max-http-header-size: 104857600



